---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.27.1
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v6.5.1
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -c .github/workflow-config/.ansiblelint.yml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
        entry: markdownlint-cli2-config .github/workflow-config/.markdownlint.yml
...
