---
- name: Playbook to install the AAP Platform
  hosts: localhost
  connection: local
  vars:
    aap_setup_down_offline_token: aabbcc
    aap_setup_working_dir: /home/username/aap_install
    aap_setup_down_type: setup
    aap_setup_inst_force: true
    aap_setup_rhel_version: 9
  vars_files:
    - inventory_vars/variables.yml
  pre_tasks:
  roles:
    - redhat_cop.aap_utilities.aap_setup_download
    - redhat_cop.aap_utilities.aap_setup_prepare
    - redhat_cop.aap_utilities.aap_setup_install
...
