---
controller_inventory_sources:
  - name: controller_config_source
    organization: config_as_code
    source: scm
    source_project: config_as_code
    source_path: "inventory_{{ env }}.yml"
    inventory: controller_config
    credential: ""
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    wait: true

  - name: custom_collections_inv
    organization: config_as_code
    source: scm
    source_project: config_as_code
    source_path: "inventory_{{ env }}.yml"
    inventory: custom_collections
    credential: ""
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    wait: true

  - name: execution_environments_inv
    organization: config_as_code
    source: scm
    source_project: config_as_code
    source_path: "inventory_{{ env }}.yml"
    inventory: execution_environments
    credential: ""
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    wait: true

  - name: ah_config_inv
    organization: config_as_code
    source: scm
    source_project: config_as_code
    source_path: "inventory_dev.yml"
    inventory: ah_config
    credential: ""
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    wait: true
...
